//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FF_LeasingVade
    {
        public int SozlesmeId { get; set; }
        public int SozlesmeVade { get; set; }
        public Nullable<System.DateTime> VadeTarihi { get; set; }
        public double VadeTutar { get; set; }
        public string ParaBirimi { get; set; }
    
        public virtual FF_LeasingSozlesme FF_LeasingSozlesme { get; set; }
    }
}
