//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FF_LeasingSozlesme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FF_LeasingSozlesme()
        {
            this.FF_LeasingVade = new HashSet<FF_LeasingVade>();
        }
    
        public int SozlesmeId { get; set; }
        public System.DateTime SozlesmeTarihi { get; set; }
        public string TedarikciKod { get; set; }
        public string TedarikciAd { get; set; }
        public string SozlesmeNo { get; set; }
        public double SozlesmeTutar { get; set; }
        public string ParaBirimi { get; set; }
        public Nullable<int> Vade { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string Aciklama { get; set; }
        public int VadeAraligi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FF_LeasingVade> FF_LeasingVade { get; set; }
    }
}
