//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KOZAEntities : DbContext
    {
        public KOZAEntities()
            : base("name=KOZAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FF_LeasingSozlesme> FF_LeasingSozlesme { get; set; }
        public virtual DbSet<FF_LeasingVade> FF_LeasingVade { get; set; }
        public virtual DbSet<tyTDR_Tedarikci> tyTDR_Tedarikci { get; set; }
    }
}
