//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tyTDR_Tedarikci
    {
        public string TDR_KodTederikci { get; set; }
        public string TDR_AdTedarikci { get; set; }
        public string TDR_AdKisa { get; set; }
        public string TDR_AckIlgili { get; set; }
        public string SKT_KodSektor { get; set; }
        public string TDT_TipTedarikci { get; set; }
        public string BLG_KodBolge { get; set; }
        public string TDA_KodAdresIRS { get; set; }
        public string TDA_KodAdresFTR { get; set; }
        public string TDA_KodAdresGNL { get; set; }
        public string TDR_AdVergiDairesi { get; set; }
        public string TDR_AdVergiNo { get; set; }
        public string TDR_Adres1 { get; set; }
        public string TDR_Adres2 { get; set; }
        public string TDR_Adres3 { get; set; }
        public string TDR_Tel1 { get; set; }
        public string TDR_Tel2 { get; set; }
        public string TDR_Fax { get; set; }
        public string TDR_Mail { get; set; }
        public string TDR_AckWeb { get; set; }
        public byte TDR_FlagSanal { get; set; }
        public byte TDR_FlagFason { get; set; }
        public byte TDR_FlagNakliyeci { get; set; }
        public byte TDR_FlagYurtdisi { get; set; }
        public byte TDR_FlagAktif { get; set; }
        public byte TDR_FlagIsletme { get; set; }
        public string TDR_KodReferans { get; set; }
        public string PRB_BirimPara { get; set; }
        public string PRB_BirimParaFatura { get; set; }
        public string ABR_KodAmbarIplikFason { get; set; }
        public string ABY_KodYerIplikFason { get; set; }
        public string AST_TipSiparis { get; set; }
        public string KTG_KodKategori { get; set; }
        public string ONC_TipOncelik { get; set; }
        public string ODT_TipOdeme { get; set; }
        public string TTP_TipTeslim { get; set; }
        public string MHS_KodMuhasebelestirme { get; set; }
        public byte TDR_FlagKumas { get; set; }
        public byte TDR_FlagIplik { get; set; }
        public byte TDR_FlagMalzeme { get; set; }
        public string TDR_AckAlisSiparis { get; set; }
        public string TDR_AckTeslimFisi { get; set; }
        public byte TDR_FlagKontrolAlisSip { get; set; }
        public double TDR_TutarMaxOtoOnay { get; set; }
        public byte TDR_FlagEgitimci { get; set; }
        public double TDR_YuzdeFireIplik { get; set; }
        public double TDR_YuzdeFireOrgu { get; set; }
        public double TDR_YuzdeFireBoya { get; set; }
        public byte TDR_FlagEFatura { get; set; }
        public byte TDR_FlagTicariEFatura { get; set; }
        public byte TDR_FlagKurFarkiCalistir { get; set; }
        public string TDR_KodTCKimlikNo { get; set; }
        public string TDR_AckNaceKod { get; set; }
        public string TDR_AckMersisNo { get; set; }
        public byte TDR_FlagKurDegerle { get; set; }
        public string SNR_KodSenaryo { get; set; }
        public string USR_KodSorumlu { get; set; }
        public byte[] TimeStamp { get; set; }
        public byte TDR_FlagFtrTutarKontrol { get; set; }
        public double TDR_OranToleransMax { get; set; }
        public double TDR_OranToleransMin { get; set; }
        public byte TDR_FlagBirey { get; set; }
        public byte TDR_FlagEIrsaliye { get; set; }
    }
}
